### ISSUE TITLE
{1.4b} - Pams Harvestcraft Spawn Eggs dont work!

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [Team-Rapture/Modpack-Hypothermia#10]
According to Zehuti

https://gyazo.com/3941725bbe368200e3c4712d663bbd6d

**Comment by juryjr** [comment]
I think that's been a issu with Pam's epic

**Comment by EPIICTHUNDERCAT** [comment]
new to me :)

**Comment by juryjr** [comment]
Ok I just know on mmds dev 2.0 it didn't work

**Comment by Traverse-Joe** [comment]
Basically reason it doesnt work is Spawn Eggs in 1.8+ call an NBT tag for the spawn and the item is <minecraft:spawn_egg> so it looks as Pam isnt registering the eggs under the new format id recommend reporting this to the mod dev thanks

**Comment by juryjr** [comment]
Closeing this issue because it's nothi g we can do about it
