### ISSUE TITLE
{1.4b} - Missing recipe for Tier1 cobble gen?

### ISSUE THREAD

**Issue by CDArena** [Team-Rapture/Modpack-Hypothermia#11]
The Tiny progressions Tier 1 cobble generator recipe is missing, but the tier 2-5 recipes are there and unusable.  The  Achievement book says to "Automate the cobblegen/craft a cobble generator", so presumably you are supposed to have the option to make the Tier1.  (Hypothermia Version 1.4b)
The Tier1 was removed in the Minetweaker script so presumably there is a reason for this, so the Achievement book entry probably needs to be adjusted. (Also, remove recipes for Tiers 2-5?)

Vanilla/manual cobble gen works; transfer node and mining upgrade works; just not the Tiny Progressions block.

**Comment by EPIICTHUNDERCAT** [comment]
It should so this must be a bug

**Comment by Traverse-Joe** [comment]
version 1.4b has been a hassle please be patient i will have these all fixed asap im working on like 10 issues 
i sense another misHap with EXU2

**Comment by GuntherDW** [comment]
It might be because I'm on a server, but I was able to look up and craft them without any issue?

http://i.imgur.com/TZo8iQm.png (ignore that this setup is doing netherrack at the moment)

**Comment by EPIICTHUNDERCAT** [comment]
interesting, seems like different things work for others and vice versa. this should all be fixed in the next update

**Comment by EPIICTHUNDERCAT** [comment]
fixed 1.4c
