### ISSUE TITLE
{1.4b} Compressed hammer destroys compressed cobble

### ISSUE THREAD

**Issue by Gavote** [Team-Rapture/Modpack-Hypothermia#12]
....yeah.

P.S. Hate to be the newb, but how would I tag this?

**Comment by EPIICTHUNDERCAT** [comment]
Yes, this is sadly a bug with EXUtils2 we are working on an update and the ex compression dev knows of this, he is working on a fix! as soon as we get that we release 1.4c! sorry for the inconvenience, for now, you have ore excavator to fall back on!

-Team Rapture

**Comment by Gavote** [comment]
Thanks!

**Comment by Traverse-Joe** [comment]
This Bug will be fixed with a simple update we are going to revert back to a previous version of EXU2 and all should go swimmingly
