### ISSUE TITLE
Water Bottle Ease!

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [Team-Rapture/Modpack-Hypothermia#13]
We have to find a way to make it harder to get water bottles:

Current ways we need to fix:

Wooden Crucible 
Tanks
Well from Pams

and many more!

If you know any please report them here!!

**Comment by Traverse-Joe** [comment]
The Only way we can alter this is to make our own thirst mod... there isnt a way to counteract this process so we just have to deal with it sadly

**Comment by CDArena** [comment]
Make sure you can still make the charcoal filters before you remove them... I had problems with the whole wood dust method and was forced to use crucibles. (They are still a slow and leaf-sucking way to make water)

**Comment by EdanStarfire** [comment]
Simple fix for the slow method:  Infinite water source + Fired Clay Bucket -> Bucket of Water + Wooden Crucible -> Wooden Crucible w/ Water + Empty Water Bottle = Clean Water Bottle, no wait, no charcoal.

Breaking method?  sure.  But it's fast.

**Comment by CDArena** [comment]
mmm - yeah, I was using actual leaves to make my water, so it didn't feel so cheaty - the downside was, it slowed my dirt production by eating into my leaves. Removing & reinstalling the latest version fixed all these problems anyhow for me.
