### ISSUE TITLE
Missing Ex Compressum Recipes

### ISSUE THREAD

**Issue by Azaler** [Team-Rapture/Modpack-Hypothermia#16]
With update 1.4c, Compressed Dust blocks from Ex Compressum don't have a crafting recipe anymore. It's not possible to create Compressed Dust using an Auto Compressor. The recipes for the Compressed Crook, Compressed Hammers, and Auto Sieve are also missing.

**Comment by Traverse-Joe** [comment]
this was fixed in 1.4d update by removing the need for excompressum hammers and sieves
(normal hammers work on compressed blocks now)

**Comment by EPIICTHUNDERCAT** [comment]
What kiba said, now use normal hammers for compressed blocks!
