### ISSUE TITLE
Unable to craft paper from wood chippings

### ISSUE THREAD

**Issue by Elef12** [Team-Rapture/Modpack-Hypothermia#18]
I am unable to craft paper in version 1.4c please help i like the mod a lot.

**Comment by Traverse-Joe** [comment]
this was fixed in 1.4d

**Comment by CDArena** [comment]
If wood dust doesn't work for you, there are a few work arounds:
use the wooden crucible to get water; sift wool to get string; sift dirt to get sugarcane seeds (vanilla recipe) or rice seeds (rice can be turned into paper too).  To "permanently" fix the wood dust, you might actually have to remove your instance of Hypothermia and re-install the latest version. (You can try backing up the World save folder to your desktop before deleting it - but sometimes important things are saved in the world save folder so your mileage may vary). 

I kind of enjoyed trying to figure out how to survive in the "bugged" version I am playing... it wasn't the author's early game route, and I found myself crooking & chopping more trees than I suspect the charcoal method would take, but I made it through!

**Comment by Elef12** [comment]
Thanks for replying at my thread i will take a look and hoepefully fix it.
Thanks :D

On 6 Feb 2017 5:18 a.m., "CDArena" <notifications@github.com> wrote:

If wood dust doesn't work for you, there are a few work arounds:
use the wooden crucible to get water; sift wool to get string; sift dirt to
get sugarcane seeds (vanilla recipe) or rice seeds (rice can be turned into
paper too). To "permanently" fix the wood dust, you might actually have to
remove your instance of Hypothermia and re-install the latest version. (You
can try backing up the World save folder to your desktop before deleting it
- but sometimes important things are saved in the world save folder so your
mileage may vary).

I kind of enjoyed trying to figure out how to survive in the "bugged"
version I am playing... it wasn't the author's early game route, and I
found myself crooking & chopping more trees than I suspect the charcoal
method would take, but I made it through!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Team-Rapture/Modpack-Hypothermia/issues/18#issuecomment-277578035>,
or mute the thread

**Comment by EPIICTHUNDERCAT** [comment]
This should have been fixed
