### ISSUE TITLE
Wanted - chest moving item

### ISSUE THREAD

**Issue by CDArena** [Team-Rapture/Modpack-Hypothermia#19]
Yeah, I'm lazy and re-organizing my base. Packing tape works for storage drawers, but I can't find any chest mover, dolly, etc. I suppose I could whip up some shape controllers and use RF tools, but that seems like overkill to move a chest across the room. Or maybe I'll just chop the chest and do it the old fashioned way...

**Comment by Traverse-Joe** [comment]
spider wands let's you move chest

**Comment by juryjr** [comment]
I forgot about them xD

**Comment by EPIICTHUNDERCAT** [comment]
Spider Wands

**Comment by EPIICTHUNDERCAT** [comment]
and bags from cyclic
