### ISSUE TITLE
Hypothermia server error

### ISSUE THREAD

**Issue by Crigamer101** [Team-Rapture/Modpack-Hypothermia#24]
I can not join into the server. the server give me the error: internal exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Tried to read NBTtag that was too big tried to allocate: 2097163bytes where max allowed 2097152 .
Please help me.
My names on the server is Crigamer101

**Comment by bahamuth** [comment]
I have the same problem, 
ingame name: bahamuth
I know for a fact that Ztorm2000 has the same problem.

A shame since it was a fun server.

**Comment by Sinfuldeity** [comment]
Refined storage will be removed in the next update. This issue should not occur anymore.
