### ISSUE TITLE
Ore Excavation 

### ISSUE THREAD

**Issue by Badpitched21** [Team-Rapture/Modpack-Hypothermia#5]
The mod Ore Excavation doesnt seem to work the  promt

An error has occured while checking OreExcavation version!

i havent mess with any of the mods and i download this pack on the curse launcher

**Comment by EPIICTHUNDERCAT** [comment]
Whats the issue exactly? 

"An error has occured while checking OreExcavation version!"  is nothing major thats just the mod version checker not working, the mod should work okay, the grave key '~' is the default key to veinmine
