### ISSUE TITLE
Wood chippings

### ISSUE THREAD

**Issue by DaeusEx** [Team-Rapture/Modpack-Hypothermia#6]
Hammering logs no longer gives wood chippings.

(Ver.: 1.4b)

**Comment by EPIICTHUNDERCAT** [comment]
Ive been told they do? are you sure this is still happening

**Comment by DaeusEx** [comment]
Yes it worked in 1.4alpha, but in 1.4b it just drops the log. (wooden and the stone tested just now in a fresh world)

update.:

It seems like an ex nihilo bug as stated on the excompressum issues tracker (with workaround).
https://github.com/blay09/ExCompressum/issues/171

**Comment by Traverse-Joe** [comment]
@DaeusEx I have wrote a temporary custom fix for this it will be out for 1.4c as well as the compressed blocks fix (which is taking the longest to fix we may just revert back to older version of EXU2) thanks for be patient

**Comment by EPIICTHUNDERCAT** [comment]
fixed in 1.4c!
