### ISSUE TITLE
Village generation

### ISSUE THREAD

**Issue by DaeusEx** [Team-Rapture/Modpack-Hypothermia#7]
Villages (with loot, food and villagers) are generated sometimes right next to spawn.

(Ver.: 1.4b)

**Comment by EPIICTHUNDERCAT** [comment]
there is not much we can do as villages are intended to spawn, we will be doing a full world revamp in upcoming updates so we may tweak their rarity!

Thank you

-Team Rapture

**Comment by EPIICTHUNDERCAT** [comment]
intended, made rare in 1.5
