### ISSUE TITLE
Heavy Sieves Issue

### ISSUE THREAD

**Issue by AngelKairi** [Team-Rapture/Modpack-Hypothermia#8]
Heavy Sieves will not recognize EU2 (ExtraUtils2) Compressed Gravel, Sand or Dust. Currently there is no means to craft the ExCompresseum variants, because there are no recipes for them. With the NoRecipeConflict mod installed, having the alternative recipe will not be an issue, so enabled them won't cause any issues. :p 

Just letting you know.

**Comment by Traverse-Joe** [comment]
so we are just gonna revert back to an earlier version of EXU2 since its EXU2 that is causing the issues in its LATEST version so we will just revert back to further anymore conflict til blay(ex compressum author) releases and update that fixes this issue

**Comment by EPIICTHUNDERCAT** [comment]
fixed 1.4c
