### ISSUE TITLE
{1.4b} - Wooden Hammer Recipe Conflict (use arrow under recipe to fix)

### ISSUE THREAD

**Issue by sinopa** [Team-Rapture/Modpack-Hypothermia#9]
when I try to make the wooden hammer it makes the wooden wrench instead 
version 1.4b

**Comment by CDArena** [comment]
I have the same issue - it prevents me from purifying water at the start. (No wooden hammer = no wood chippings. Stone hammer doesn't make chippings)

Temporary work around: Make a wood crucible and fill with saplings to create water; remove with bottle

**Comment by EPIICTHUNDERCAT** [comment]
@CDArena @sinopa you can use the mini arrow next to the crafting output to change conflicting recipes!

**Comment by Gavote** [comment]
@EPIICTHUNDERCAT  Thank you, I'd been wondering what the arrow was for!

**Comment by EPIICTHUNDERCAT** [comment]
@Gavote yep the arrow is for conflicting recipes! 

-Stay Warm!

**Comment by EPIICTHUNDERCAT** [comment]
fixed 1.4c

**Comment by Gavote** [comment]
WOO!
